version: "3"
services:
  kserver:
    image: marcgc/k19:kserver
    container_name: kserver.edt.org
    hostname: kserver.edt.org
    ports:
      - "88:88"
      - "464:464"
      - "749:749"
    networks:
      - mynet
  ldap:
    image: marcgc/ldapserver19
    container_name: ldap.edt.org
    hostname: ldat.edt.org
    ports:
      - "389:389"
    networks:
      - mynet
  sshd:
    image: marcgc/k19:sshdpl
    container_name: sshd.edt.org
    hostname: sshd.edt.org
    ports:
      - "1022:22"
    networks:
      - mynet
networks:
  mynet: